fisher_robot: # this must correspond to namespace
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController # must install with apt-get install ros-melodic-effort-controllers
    joint: joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
    set_point: 0.2
    publish_rate: 20
  # joint2_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: joint2
  #   pid: {p: 100.0, i: 0.01, d: 10.0}
