joint_limits:

    joint1:
      has_position_limits: true
      min_position: -3.14
      max_position: 1.57
      has_velocity_limits: false
      max_velocity: 1.5
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: true
      max_effort: 450
      min_effort: 0
